### ISSUE TITLE
window not defined in jest-puppeteer environment

### ISSUE THREAD

**Issue by shivijais** [smooth-code/jest-puppeteer#386] opened 2021-01-27 16:05 UTC
I am trying to write a test which uses puppeteer API page.evaluate and uses window variable. But I see the error:

```
The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: window is not defined
```

Is there a workaround for this? Are we supposed to not use 'window' when writing tests using jest-puppeteer?

I cannot change the test-environment to jest-dom because I'm using page which is coming from jest-puppeteer environment.

**Comment by jameskip** [comment] 2021-01-29 03:41
You should be able to put this in your jest configuration file.

```json
"jest": {
    "setupTestFrameworkScriptFile": "tests/setup.js"
}
```

**Comment by UziTech** [comment] 2021-04-08 22:50
duplicate of #295

**Closed by UziTech** 2021-04-08 22:50 UTC
Labels: duplicate 👯‍♀️
