### ISSUE TITLE
Root password asked to start dev server

### ISSUE THREAD

**Issue by CyrilQuandalle** [smooth-code/jest-puppeteer#104] opened 2018-08-03 08:55 UTC
Hi,
I know there is already a similar issue but with no answer so I reiterate.
I have a problem while starting my dev server with the configuration set in the jest-puppeteer.config.js file.
The cli keep asking me for my root password to start the server, which is not very good for automation ;-).

here is the content of my configuration file :

`module.exports = {
  server: {
    command: 'npm start',
    port: 3010
  },
  launch: {
    dumpio: true,
    headless: true
  }
}`

FYI: If I enter the password the server start as usual.

Thank you very much in advance

**Comment by neoziro** [comment] 2018-08-15 21:14
Hello @CyrilQuandalle, I think it is a problem in your server. You should try to run "npm start" without Jest Puppeteer and see what's going on. The requirement of a root password can be multiple things: a usage of a restricted port, the execution rights of the process...

This issue is not relative to Jest Puppeteer but I let it opened if someone want to help.

**Comment by neoziro** [comment] 2018-08-15 21:30
Duplicate of #96

**Closed** 2018-08-15 21:30 UTC
