### ISSUE TITLE
toFill cannot fill input with empty string

### ISSUE THREAD

**Issue by peterekepeter** [smooth-code/jest-puppeteer#372] opened 2020-08-11 09:55 UTC
## expect(page).toFill cannot fill input with empty string

My use case is trying to test input validation, some of the validation tries to see if input are empty or not,
my current workaround is to execute a javascript on the page.

``` javascript
await expect(page).toFill('input', '');
```

## To Reproduce

Try to fill input with empty string, it doesn't do anything.

## Expected behavior

Input should be empty after execution.

**Comment by MatthiasEngh** [comment] 2020-11-14 05:17
ah interesting! I didn't get it immediately, thinking that filling an input with an empty string should rightfully leave it blank, but since filling it with any string overrides the previous value, an empty string should clear the input. I reproduced this, it's the only case where the previous content isn't overridden and I think it should be fixed

**Comment by peterekepeter** [comment] 2020-11-15 06:18
Yes, I was trying to set up a test case, to test validation behavior of empty input fields in a form, and noticed that I couldn't do it with toFill... I did make a workaround using page.evaluate but I would expect toFill to be able to handle this

**Closed** 2021-04-16 04:11 UTC
Labels: bug 🐛
